-- use this file to map the AP location ids to your locations
-- first value is the code of the target location/item and the second is the item type override (feel free to expand the table with any other values you might need (i.e. special initial values, increments, etc.)!)
-- to reference a location in Pop use @ in the beginning and then path to the section (more info: https://github.com/black-sliver/PopTracker/blob/master/doc/PACKS.md#locations)
-- to reference an item use it's code
-- here are the SM locations as an example: https://github.com/Cyb3RGER/sm_ap_tracker/blob/main/scripts/autotracking/location_mapping.lua
BASE_LOCATION_ID = 0
LOCATION_MAPPING = {
	[23] = {{"@Resistance Base/Second Floor/Room 02D (Mission Set 2)"}},
	[44] = {{"@Resistance Base/Rocinolle/Talk to Rocinolle (Mission Set 4)"}},
	[58] = {{"@Resistance Base/Right Tower/Talk to Right Tower Soldier (Mission Set 1)"}},
	[92] = {{"@Resistance Base/Cerveau/Talk to Cerveau (Mission Set 1)"}},
	[99] = {{"@Resistance Base/Third Floor/Room 03D"}},
	[106] = {{"@Resistance Base/Rooftop/Left Corner of Rooftop"}},
	[107] = {{"@Resistance Base/Andrew/Talk to Andrew (Mission Set 2)"}},
	[116] = {{"@Resistance Base/Alouette/Talk to Alouette (Mission Set 2)"}},
	[165] = {{"@Resistance Base/Alouette/Near Alouette"}},
	[166] = {{"@Resistance Base/Cerveau/Near Cerveau"}},
	[167] = {{"@Resistance Base/Rocinolle/Talk to Rocinolle (Mission Set 1)"}},
	[168] = {{"@Resistance Base/Second Foor Hall/Second Floor Hall"}},
	[169] = {{"@Resistance Base/Hibou/Talk to Hibou (Mission Set 2)"}},
	[170] = {{"@Resistance Base/Rocinolle/Near Rocinolle"}},
	[171] = {{"@Resistance Base/First Floor Left/Left Room on 1st Floor"}},
	[172] = {{"@Resistance Base/First Floor Right/Right Room on 1st Floor"}},
	[173] = {{"@Resistance Base/Hirondelle/Talk to Hirondelle (Mission Set 2)"}},
	[174] = {{"@Resistance Base/Doigt/Talk to Doigt (Mission Set 2)"}},
	[175] = {{"@Resistance Base/Menart/Talk to Menart (Mission Set 1)"}},
	[176] = {{"@Resistance Base/Pic/Near Pic"}},

	[133] = {{"@Derelict Spacecraft/5th Grand Cannon Kill/Kill Check"}},
	[140] = {{"@Derelict Spacecraft/3rd Shrimpolin Kill/Kill Check"}},
	[158] = {{"@Derelict Spacecraft/4th Shotcounter Kill/Kill Check"}},
	[156] = {{"@Derelict Spacecraft/4th Batring Kill/Kill Check"}},
	[24] = {{"@Derelict Spacecraft/024/1st Pit Secret Wall"}},
	[37] = {{"@Derelict Spacecraft/037/Ledge Past Entrance"}},
	[50] = {{"@Derelict Spacecraft/050/Ice Side Room"}},
	[101] = {{"@Derelict Spacecraft/101/Ledge in Top Right"}},
	[111] = {{"@Derelict Spacecraft/111/Final Ascent Bottom"}},
	[7] = {{"@Derelict Spacecraft/007/Final Ascent Ledge"}},

	[141] = {{"@Aegis Volcano Base/3rd Volcaire Kill/Kill Check"}},
	[146] = {{"@Aegis Volcano Base/4th Lamplort Kill/Kill Check"}},
	[47] = {{"@Aegis Volcano Base/047/Ledge Above Lava"}},
	[102] = {{"@Aegis Volcano Base/102/1st Box Inside"}},
	[26] = {{"@Aegis Volcano Base/026/Platform Above First Room"}},
	[114] = {{"@Aegis Volcano Base/114/Push 1st Container"}},
	[73] = {{"@Aegis Volcano Base/073/Container Before Miniboss, Platform After"}},
	[152] = {{"@Aegis Volcano Base/152/10th Crossbyne Kill (Miniboss)"}},
	[72] = {{"@Aegis Volcano Base/072/Lamplort Box"}},
	[8] = {{"@Aegis Volcano Base/008/Top Gabyoall Box"}},

	[159] = {{"@Oceanic Highway Ruins/4th Sharkseal X Kill/Kill Check"}},
	[161] = {{"@Oceanic Highway Ruins/3rd Icebon Kill/Kill Check"}},
	[160] = {{"@Oceanic Highway Ruins/4th Shelluno Kill/Kill Check"}},
	[5] = {{"@Oceanic Highway Ruins/005/1st Pit Breakable"}},
	[75] = {{"@Oceanic Highway Ruins/075/1st Underwater Pit"}},
	[9] = {{"@Oceanic Highway Ruins/009/Above Cyber Door"}},
	[59] = {{"@Oceanic Highway Ruins/059/Above 1st Spike Wall"}},
	[79] = {{"@Oceanic Highway Ruins/079/Miniboss Kill"}},
	[49] = {{"@Oceanic Highway Ruins/049/Spiked Platforms"}},
	[113] = {{"@Oceanic Highway Ruins/113/Left of Final Button"}},

	[147] = {{"@Weapons Repair Factory/5th Lemmingles Kill/Kill Check"}},
	[131] = {{"@Weapons Repair Factory/5th Deathlock Kill/Kill Check"}},
	[52] = {{"@Weapons Repair Factory/3rd Lemmingles Generator Kill/Kill Check"}},
	[12] = {{"@Weapons Repair Factory/012/Below 3rd Hammer"}},
	[115] = {{"@Weapons Repair Factory/115/Hit 3rd Hammer"}},
	[104] = {{"@Weapons Repair Factory/104/Past 4th Hammer"}},
	[93] = {{"@Weapons Repair Factory/093/Miniboss Kill"}},
	[100] = {{"@Weapons Repair Factory/100/Behind Lemmingles Generator"}},
	[84] = {{"@Weapons Repair Factory/084/Conveyor Descent Ledge"}},
	[53] = {{"@Weapons Repair Factory/053/Ladder Into Junk"}},

	[145] = {{"@Old Residential/5th Seimeran Kill/Kill Check"}},
	[135] = {{"@Old Residential/3rd Pillar Cannon Kill/Kill Check"}},
	[39] = {{"@Old Residential/039/1st Door"}},
	[1] = {{"@Old Residential/001/Stump Door"}},
	[112] = {{"@Old Residential/112/Floor Breakables"}},
	[74] = {{"@Old Residential/074/Left Fork Door"}},
	[67] = {{"@Old Residential/067/Miniboss Kill"}},
	[28] = {{"@Old Residential/028/Box After Bombers"}},
	[48] = {{"@Old Residential/048/Top Right Secret Door"}},
	[13] = {{"@Old Residential/013/2 Pits Left of Secret Door Exit"}},

	[139] = {{"@Missile Factory/4th Eye Cannon Kill/Kill Check"}},
	[127] = {{"@Missile Factory/4th Pantheon Guardian Kill/Kill Check"}},
	[138] = {{"@Missile Factory/4th Generator Cannon Kill/Kill Check"}},
	[98] = {{"@Missile Factory/6th Generator Cannon Spawn Kill/Kill Check"}},
	[57] = {{"@Missile Factory/057/Spiky Side Room"}},
	[30] = {{"@Missile Factory/030/By Cyber Door"}},
	[90] = {{"@Missile Factory/090/2nd Conveyor Slopes Ledge"}},
	[55] = {{"@Missile Factory/055/Left of 2nd Conveyor Slope"}},
	[117] = {{"@Missile Factory/117/Above 2nd Conveyor Slope"}},
	[21] = {{"@Missile Factory/021/Top Left Ledge"}},

	[91] = {{"@Twilight Desert/5th Shrimpolin Kill/Kill Check"}},
	[153] = {{"@Twilight Desert/5th Flopper Kill/Kill Check"}},
	[154] = {{"@Twilight Desert/5th PurpleNerple Kill/Kill Check"}},
	[85] = {{"@Twilight Desert/085/After Long Quicksand"}},
	[89] = {{"@Twilight Desert/089/Miniboss Kill"}},
	[31] = {{"@Twilight Desert/031/Above 1st Pillar Cannon"}},
	[22] = {{"@Twilight Desert/022/Above 2nd Cyber Door"}},
	[105] = {{"@Twilight Desert/105/After 1st Helicopter"}},
	[118] = {{"@Twilight Desert/118/After 1st Helicopter"}},
	[65] = {{"@Twilight Desert/065/2nd Helicopter Kill/Kill Check"}},

	[157] = {{"@Forest of Anatre/5th Mellnet Kill/Kill Check"}},
	[134] = {{"@Forest of Anatre/7th Tile Cannon Kill/Kill Check"}},
	[63] = {{"@Forest of Anatre/063/Treetops Above Start"}},
	[2] = {{"@Forest of Anatre/002/Ledge Above 1st Door"}},
	[71] = {{"@Forest of Anatre/071/3rd Button Lower Path"}},
	[14] = {{"@Forest of Anatre/014/Above 7th Button"}},
	[119] = {{"@Forest of Anatre/119/7th Button Lower Path"}},
	[108] = {{"@Forest of Anatre/108/8th Button Spike Pit"}},
	[76] = {{"@Forest of Anatre/076/Above 9th Button"}},
	[40] = {{"@Forest of Anatre/040/Breakables Below Boss Room"}},

	[132] = {{"@Frontline Ice Base/3rd Gyro Cannon Kill/Kill Check"}},
	[128] = {{"@Frontline Ice Base/3rd Pantheon Aqua Kill/Kill Check"}},
	[136] = {{"@Frontline Ice Base/3rd Heavy Cannon Kill/Kill Check"}},
	[66] = {{"@Frontline Ice Base/066/Top Route Tower"}},
	[109] = {{"@Frontline Ice Base/109/Top Route Indoor Ledge"}},
	[15] = {{"@Frontline Ice Base/015/Top Route Pipe Passage"}},
	[32] = {{"@Frontline Ice Base/032/Ledge Before 2nd Door"}},
	[35] = {{"@Frontline Ice Base/035/Ledge After 2nd Door"}},
	[120] = {{"@Frontline Ice Base/120/Heavy Cannon Box"}},
	[68] = {{"@Frontline Ice Base/068/Final Ascent"}},

	[137] = {{"@Area X-2/4th Capsule Cannon Kill/Kill Check"}},
	[110] = {{"@Area X-2/110/1st Descent Ledge"}},
	[121] = {{"@Area X-2/121/1st Descent Bottom"}},
	[62] = {{"@Area X-2/062/Ledge Above Platforms"}},
	[34] = {{"@Area X-2/034/1st Ascent Top"}},
	[42] = {{"@Area X-2/042/Spiky Ascent Bottom"}},
	[70] = {{"@Area X-2/070/Spiky Ascent Middle"}},
	[77] = {{"@Area X-2/077/Spiky Ascent Top"}},
	[69] = {{"@Area X-2/069/Platforms Side Room (Lower)"}},
	[61] = {{"@Area X-2/061/Platforms Side Room (Upper)"}},

	[155] = {{"@Energy Facility/9th Mothjiro Kill/Kill Check"}},
	[150] = {{"@Energy Facility/4th Snakecord Kill/Kill Check"}},
	[56] = {{"@Energy Facility/056/Box Past 1st Cyber Door"}},
	[124] = {{"@Energy Facility/124/1st Ascent Right Path"}},
	[82] = {{"@Energy Facility/082/Box After 1st Ascent"}},
	[149] = {{"@Energy Facility/149/Miniboss Kill"}},
	[64] = {{"@Energy Facility/064/Girder Ride Left"}},
	[95] = {{"@Energy Facility/095/Girder Ride Right"}},
	[78] = {{"@Energy Facility/078/Snakecord Guarded Secret Wall"}},
	[4] = {{"@Energy Facility/004/Girder Maze Top Left"}},

	[162] = {{"@Snowy Plains/4th Shellcrawler Kill/Kill Check"}},
	[130] = {{"@Snowy Plains/4th Pantheon Base Kill/Kill Check"}},
	[3] = {{"@Snowy Plains/003/2nd Slope Secret Wall"}},
	[29] = {{"@Snowy Plains/029/1st Rail Set Start"}},
	[25] = {{"@Snowy Plains/025/1st Rail Set Middle"}},
	[103] = {{"@Snowy Plains/103/1st Rail Set 2nd Pit Secret Wall"}},
	[46] = {{"@Snowy Plains/Miniboss/046: 5th Miniboss Snowball Kill"}},
	[60] = {{"@Snowy Plains/Miniboss/060: Miniboss Kill"}},
	[123] = {{"@Snowy Plains/123/2nd Rail Set Start"}},
	[86] = {{"@Snowy Plains/086/2nd Rail Set Middle"}},

	[125] = {{"@Sunken Library/125/Ledge Above First Pool"}},
	[51] = {{"@Sunken Library/051/Under Second Pool"}},
	[43] = {{"@Sunken Library/043/Last Exposed Wire"}},
	[33] = {{"@Sunken Library/033/Past Exposed Wires"}},
	[94] = {{"@Sunken Library/094/End of 1st Passage"}},
	[96] = {{"@Sunken Library/096/Above 1st Door"}},
	[10] = {{"@Sunken Library/Dr. Weil Data/Labyrinth Data Check"}},
	[17] = {{"@Sunken Library/Omega Data/Labyrinth Data Check"}},
	[16] = {{"@Sunken Library/Dark Elf Data/Labyrinth Data Check"}},
	[18] = {{"@Sunken Library/Elf Wars Data/Labyrinth Data Check"}},

	[148] = {{"@Giant Elevator/5th Cattatank Kill/Kill Check"}},
	[144] = {{"@Giant Elevator/6th Shotloid Kill/Kill Check"}},
	[129] = {{"@Giant Elevator/4th Pantheon Fist Kill/Kill Check"}},
	[45] = {{"@Giant Elevator/045/1st Passage High Ledges"}},
	[41] = {{"@Giant Elevator/041/1st Passage High Ledges"}},
	[80] = {{"@Giant Elevator/080/1st Passage High Ledges"}},
	[54] = {{"@Giant Elevator/054/1st Passage High Ledges"}},
	[122] = {{"@Giant Elevator/122/1st Descent Ledge"}},
	[27] = {{"@Giant Elevator/027/1st Descent Bottom Left Breakable"}},
	[88] = {{"@Giant Elevator/088/Miniboss Kill"}},

	[163] = {{"@Sub Arcadia/5th Cannonhopper Kill/Kill Check"}},
	[143] = {{"@Sub Arcadia/3rd Petatria Kill/Kill Check"}},
	[142] = {{"@Sub Arcadia/5th Claveker Kill/Kill Check"}},
	[36] = {{"@Sub Arcadia/036/1st Descent Ledge"}},
	[81] = {{"@Sub Arcadia/081/Platforms Room Under Start"}},
	[38] = {{"@Sub Arcadia/038/Platforms Room Top Left"}},
	[6] = {{"@Sub Arcadia/006/Phantom Kill (Platforms Top Left, in Cyberspace)"}},
	[180] = {{"@Sub Arcadia/180/Platforms Room Bottom"}},
	[87] = {{"@Sub Arcadia/087/Box Past 1st Door"}},
	[83] = {{"@Sub Arcadia/083/Final Descent Left"}},

	[126] = {{"@Abandoned Research Laboratory/5th Pantheon Hunter Kill/Kill Check"}},
	[97] = {{"@Abandoned Research Laboratory/097/1st Box"}},
	[177] = {{"@Abandoned Research Laboratory/177/Ledge Above Spike Zone"}},
	[151] = {{"@Abandoned Research Laboratory/151/Ice Zone Box"}},
	[19] = {{"@Abandoned Research Laboratory/019/Ice Zone Box"}},
	[20] = {{"@Abandoned Research Laboratory/020/Ice Zone Box"}},
	[178] = {{"@Abandoned Research Laboratory/178/Ice Zone Alarm Ledge"}},
	[164] = {{"@Abandoned Research Laboratory/164/Ice Zone Box"}},
	[179] = {{"@Abandoned Research Laboratory/179/Final Section Box"}},
	[11] = {{"@Abandoned Research Laboratory/011/Final Section Box"}},

	[181] = {{"@Complete Derelict Spacecraft"}},
	[182] = {{"@Complete Aegis Volcano Base"}},
	[183] = {{"@Complete Oceanic Highway Ruins"}},
	[184] = {{"@Complete Weapons Repair Factory"}},
	[185] = {{"@Complete Old Residential"}},
	[186] = {{"@Complete Missile Factory"}},
	[187] = {{"@Complete Twilight Desert"}},
	[188] = {{"@Complete Forest of Anatre"}},
	[189] = {{"@Complete Frontline Ice Base"}},
	[190] = {{"@Complete Area X-2"}},
	[191] = {{"@Complete Energy Facility"}},
	[192] = {{"@Complete Snowy Plains"}},
	[193] = {{"@Complete Sunken Library"}},
	[194] = {{"@Complete Giant Elevator"}},
	[195] = {{"@Complete Sub Arcadia"}},
	[196] = {{"@Complete Abandoned Research Laboratory"}},

	[197] = {{"@Complete Oceanic Highway Ruins/Collect Ice Body Chip"}},
	[198] = {{"@Complete Weapons Repair Factory/Collect Thunder Body Chip"}},
	[199] = {{"@Complete Aegis Volcano Base/Collect Flame Body Chip"}},
	[200] = {{"@Complete Old Residential/Collect Light Body Chip"}},
	[201] = {{"@Complete Giant Elevator/Collect Absorber Body Chip"}},
	[202] = {{"@Complete Snowy Plains/Collect Spike Foot Chip"}},
	[203] = {{"@Complete Area X-2/Collect Quick Foot Chip"}},
	[204] = {{"@Complete Energy Facility/Collect Double Jump Foot Chip"}},
	[205] = {{"@Complete Sunken Library/Collect Shadow Dash Foot Chip"}},

	[206] = {{"@Complete Derelict Spacecraft/A+ Rank Clear"}},
	[207] = {{"@Complete Aegis Volcano Base/A+ Rank Clear"}},
	[208] = {{"@Complete Oceanic Highway Ruins/A+ Rank Clear"}},
	[209] = {{"@Complete Weapons Repair Factory/A+ Rank Clear"}},
	[210] = {{"@Complete Old Residential/A+ Rank Clear"}},
	[211] = {{"@Complete Missile Factory/A+ Rank Clear"}},
	[212] = {{"@Complete Twilight Desert/A+ Rank Clear"}},
	[213] = {{"@Complete Forest of Anatre/A+ Rank Clear"}},
	[214] = {{"@Complete Frontline Ice Base/A+ Rank Clear"}},
	[215] = {{"@Complete Area X-2/A+ Rank Clear"}},
	[216] = {{"@Complete Energy Facility/A+ Rank Clear"}},
	[217] = {{"@Complete Snowy Plains/A+ Rank Clear"}},
	[218] = {{"@Complete Sunken Library/A+ Rank Clear"}},
	[219] = {{"@Complete Giant Elevator/A+ Rank Clear"}},
	[220] = {{"@Complete Sub Arcadia/A+ Rank Clear"}},

	[221] = {{"@Old Residential/Subtank"}},
	[222] = {{"@Forest of Anatre/Subtank"}},
	[226] = {{"@Resistance Base/Cerveau/Collect Recoil Rod"}},
	[227] = {{"@Resistance Base/Cerveau/Collect Shield Boomerang"}},
}
